// USB Mass Storage Mode
//
// Presents the LcdTap framebuffer as a single read-only FAT12 disk image
// containing one file: frame_buffer.png (PNG 24bpp, uncompressed DEFLATE).
//
// PNG is generated byte-by-byte on demand (seekable, zero extra RAM).
// Checksums (Adler-32, CRC32) are precomputed once from the frozen framebuf.

#include "usb_msc.hpp"

#include <cstring>

#include "hardware/gpio.h"
#include "hardware/watchdog.h"
#include "pico/stdlib.h"
#include "pico/unique_id.h"
#include "tusb.h"

#include "config.h"

// =============================================================================
// CRC32 (IEEE 802.3 / zlib / PNG)
// =============================================================================

static uint32_t crc32_init() { return 0xFFFFFFFFu; }

static uint32_t crc32_update(uint32_t crc, const uint8_t *data, size_t len) {
  for (size_t i = 0; i < len; ++i) {
    crc ^= data[i];
    for (int j = 0; j < 8; ++j) crc = (crc >> 1) ^ (0xEDB88320u & -(crc & 1u));
  }
  return crc;
}

static uint32_t crc32_finalize(uint32_t crc) { return crc ^ 0xFFFFFFFFu; }

static uint32_t crc32_buf(const uint8_t *data, size_t len) {
  return crc32_finalize(crc32_update(crc32_init(), data, len));
}

// =============================================================================
// Adler-32 (zlib checksum used in PNG zlib stream)
// =============================================================================

static void adler32_update(uint32_t &s1, uint32_t &s2, uint8_t byte) {
  s1 = (s1 + byte) % 65521u;
  s2 = (s2 + s1) % 65521u;
}

// =============================================================================
// PNG snapshot
// =============================================================================

// ROW_STRIDE: 5 (deflate block header) + 1 (filter byte) + W*3 (RGB888 pixels)
// IDAT_PAYLOAD_SIZE: 2 (zlib header) + H * ROW_STRIDE + 4 (Adler-32)
// PNG_FILE_SIZE: 8 (sig) + 25 (IHDR) + 8 (IDAT hdr) + IDAT_PAYLOAD_SIZE
//                + 4 (IDAT CRC) + 12 (IEND)

struct PngSnapshot {
  const uint16_t *framebuf;
  uint32_t width;
  uint32_t height;
  uint32_t adler32;
  uint32_t ihdr_crc32;
  uint32_t idat_crc32;
  uint32_t file_size;
  uint32_t idat_payload_size;
};

static PngSnapshot gSnap;
static bool gSnapReady = false;
static bool gVolumeSerialUpdateReq = false;
static lcdtap::LcdTap *gInstUsb = nullptr;
static uint32_t gFileSizeUsb = 0u;
static uint32_t gVolumeSerialUsb = 0x04030201u;

static inline void rgb565_to_rgb888(uint16_t px, uint8_t &r, uint8_t &g,
                                    uint8_t &b) {
  uint8_t r5 = (px >> 11) & 0x1Fu;
  uint8_t g6 = (px >> 5) & 0x3Fu;
  uint8_t b5 = px & 0x1Fu;
  r = (r5 << 3) | (r5 >> 2);
  g = (g6 << 2) | (g6 >> 4);
  b = (b5 << 3) | (b5 >> 2);
}

static void png_snapshot_init(PngSnapshot *snap, lcdtap::LcdTap *inst) {
  const lcdtap::LcdTapConfig cfg = inst->getConfig();
  snap->framebuf = inst->getFramebuf();
  snap->width = cfg.lcdWidth;
  snap->height = cfg.lcdHeight;

  const uint32_t W = snap->width;
  const uint32_t H = snap->height;
  const uint32_t ROW_STRIDE = 5u + 1u + W * 3u;
  const uint32_t LEN = 1u + W * 3u;  // filter byte + pixels per row
  const uint32_t IDAT_PAYLOAD_SIZE = 2u + H * ROW_STRIDE + 4u;
  snap->idat_payload_size = IDAT_PAYLOAD_SIZE;
  snap->file_size = 8u + 25u + (4u + 4u + IDAT_PAYLOAD_SIZE + 4u) + 12u;

  // ---- IHDR CRC32 (covers "IHDR" + 13 data bytes) ----
  uint8_t ihdr_crc_buf[17];
  ihdr_crc_buf[0] = 'I';
  ihdr_crc_buf[1] = 'H';
  ihdr_crc_buf[2] = 'D';
  ihdr_crc_buf[3] = 'R';
  ihdr_crc_buf[4] = (W >> 24) & 0xFF;
  ihdr_crc_buf[5] = (W >> 16) & 0xFF;
  ihdr_crc_buf[6] = (W >> 8) & 0xFF;
  ihdr_crc_buf[7] = W & 0xFF;
  ihdr_crc_buf[8] = (H >> 24) & 0xFF;
  ihdr_crc_buf[9] = (H >> 16) & 0xFF;
  ihdr_crc_buf[10] = (H >> 8) & 0xFF;
  ihdr_crc_buf[11] = H & 0xFF;
  ihdr_crc_buf[12] = 8;  // bit depth
  ihdr_crc_buf[13] = 2;  // color type: RGB
  ihdr_crc_buf[14] = 0;  // compression: deflate
  ihdr_crc_buf[15] = 0;  // filter: adaptive
  ihdr_crc_buf[16] = 0;  // interlace: none
  snap->ihdr_crc32 = crc32_buf(ihdr_crc_buf, 17);

  // ---- Adler-32 + IDAT CRC32 in one framebuf pass ----
  uint32_t adler_s1 = 1u, adler_s2 = 0u;
  uint32_t idat_crc = crc32_init();

  const uint8_t idat_type[4] = {'I', 'D', 'A', 'T'};
  idat_crc = crc32_update(idat_crc, idat_type, 4);

  const uint8_t zlib_hdr[2] = {0x78, 0x01};
  idat_crc = crc32_update(idat_crc, zlib_hdr, 2);

  for (uint32_t y = 0; y < H; ++y) {
    bool last_row = (y == H - 1u);
    uint16_t len16 = static_cast<uint16_t>(LEN);
    uint16_t nlen16 = ~len16;
    uint8_t blk_hdr[5] = {
        static_cast<uint8_t>(last_row ? 0x01u : 0x00u),
        static_cast<uint8_t>(len16 & 0xFFu),
        static_cast<uint8_t>(len16 >> 8u),
        static_cast<uint8_t>(nlen16 & 0xFFu),
        static_cast<uint8_t>(nlen16 >> 8u),
    };
    idat_crc = crc32_update(idat_crc, blk_hdr, 5);

    const uint8_t filter_byte = 0x00u;
    idat_crc = crc32_update(idat_crc, &filter_byte, 1);
    adler32_update(adler_s1, adler_s2, filter_byte);

    for (uint32_t x = 0; x < W; ++x) {
      uint8_t r, g, b;
      rgb565_to_rgb888(snap->framebuf[y * W + x], r, g, b);
      const uint8_t px[3] = {r, g, b};
      idat_crc = crc32_update(idat_crc, px, 3);
      adler32_update(adler_s1, adler_s2, r);
      adler32_update(adler_s1, adler_s2, g);
      adler32_update(adler_s1, adler_s2, b);
    }
  }

  snap->adler32 = (adler_s2 << 16u) | adler_s1;

  const uint8_t adler_be[4] = {
      static_cast<uint8_t>((snap->adler32 >> 24u) & 0xFFu),
      static_cast<uint8_t>((snap->adler32 >> 16u) & 0xFFu),
      static_cast<uint8_t>((snap->adler32 >> 8u) & 0xFFu),
      static_cast<uint8_t>(snap->adler32 & 0xFFu),
  };
  idat_crc = crc32_update(idat_crc, adler_be, 4);
  snap->idat_crc32 = crc32_finalize(idat_crc);
}

// Returns the byte at file offset `offset` within the PNG stream.
// Computed entirely from the snapshot (no buffering needed).
static uint8_t png_byte_at(const PngSnapshot *snap, uint32_t offset) {
  const uint32_t W = snap->width;
  const uint32_t H = snap->height;
  const uint32_t ROW_STRIDE = 5u + 1u + W * 3u;
  const uint32_t LEN = 1u + W * 3u;

  // PNG signature [0..7]
  static const uint8_t PNG_SIG[8] = {137, 80, 78, 71, 13, 10, 26, 10};
  if (offset < 8u) return PNG_SIG[offset];

  // IHDR chunk [8..32]: 4 (len) + 4 (type) + 13 (data) + 4 (crc) = 25 bytes
  if (offset < 33u) {
    uint32_t i = offset - 8u;
    // Length field: 0x0000000D = 13
    if (i < 4u) return i == 2u ? 0x00u : i == 3u ? 0x0Du : 0x00u;
    i -= 4u;
    // Type field: "IHDR"
    if (i < 4u) return static_cast<uint8_t>("IHDR"[i]);
    i -= 4u;
    // Data
    if (i < 13u) {
      if (i < 4u) return static_cast<uint8_t>((W >> (24u - 8u * i)) & 0xFFu);
      i -= 4u;
      if (i < 4u) return static_cast<uint8_t>((H >> (24u - 8u * i)) & 0xFFu);
      i -= 4u;
      const uint8_t rest[5] = {8, 2, 0, 0, 0};
      return rest[i];
    }
    i -= 13u;
    // CRC32
    return static_cast<uint8_t>((snap->ihdr_crc32 >> (24u - 8u * i)) & 0xFFu);
  }

  // IDAT chunk [33..33 + 4 + 4 + IDAT_PAYLOAD_SIZE + 4 - 1]
  const uint32_t IDAT_PAYLOAD_SIZE = snap->idat_payload_size;
  const uint32_t IDAT_TOTAL = 4u + 4u + IDAT_PAYLOAD_SIZE + 4u;
  const uint32_t IDAT_END = 33u + IDAT_TOTAL;

  if (offset < IDAT_END) {
    uint32_t i = offset - 33u;

    // Chunk length (4 bytes BE)
    if (i < 4u) {
      return static_cast<uint8_t>((IDAT_PAYLOAD_SIZE >> (24u - 8u * i)) &
                                  0xFFu);
    }
    i -= 4u;

    // Chunk type "IDAT"
    if (i < 4u) return static_cast<uint8_t>("IDAT"[i]);
    i -= 4u;

    // ---- IDAT payload ----
    // zlib header
    if (i < 2u) return i == 0u ? 0x78u : 0x01u;
    i -= 2u;

    // DEFLATE stored blocks
    const uint32_t BLOCKS_SIZE = H * ROW_STRIDE;
    if (i < BLOCKS_SIZE) {
      uint32_t row = i / ROW_STRIDE;
      uint32_t col = i % ROW_STRIDE;

      // DEFLATE stored block header (5 bytes)
      if (col < 5u) {
        bool last_row = (row == H - 1u);
        uint16_t len16 = static_cast<uint16_t>(LEN);
        uint16_t nlen16 = ~len16;
        switch (col) {
          case 0: return last_row ? 0x01u : 0x00u;
          case 1: return static_cast<uint8_t>(len16 & 0xFFu);
          case 2: return static_cast<uint8_t>(len16 >> 8u);
          case 3: return static_cast<uint8_t>(nlen16 & 0xFFu);
          case 4: return static_cast<uint8_t>(nlen16 >> 8u);
        }
      }
      col -= 5u;

      // Filter byte
      if (col == 0u) return 0x00u;
      col -= 1u;

      // RGB888 pixel data
      uint32_t x = col / 3u;
      uint32_t ch = col % 3u;
      uint8_t r, g, b;
      rgb565_to_rgb888(snap->framebuf[row * W + x], r, g, b);
      return ch == 0u ? r : ch == 1u ? g : b;
    }
    i -= BLOCKS_SIZE;

    // Adler-32 (4 bytes BE)
    if (i < 4u) {
      return static_cast<uint8_t>((snap->adler32 >> (24u - 8u * i)) & 0xFFu);
    }
    i -= 4u;

    // IDAT chunk CRC32 (4 bytes BE)
    if (i < 4u) {
      return static_cast<uint8_t>((snap->idat_crc32 >> (24u - 8u * i)) & 0xFFu);
    }
    return 0u;
  }

  // IEND chunk [IDAT_END..IDAT_END+11]: length=0, "IEND", crc=0xAE426082
  if (offset < snap->file_size) {
    static const uint8_t IEND[12] = {0,   0,   0,    0,    'I',  'E',
                                     'N', 'D', 0xAE, 0x42, 0x60, 0x82};
    return IEND[offset - IDAT_END];
  }

  return 0u;
}

// =============================================================================
// Virtual FAT12 disk
// =============================================================================

static constexpr uint32_t DISK_SECTOR_SIZE = 512u;
static constexpr uint32_t DISK_SECTOR_COUNT = 1024u;  // 512 KB virtual disk
static constexpr uint32_t FAT_SECTOR_START = 1u;
static constexpr uint32_t FAT_SECTOR_COUNT =
    3u;  // holds up to 1021 FAT12 entries
static constexpr uint32_t ROOT_DIR_SECTOR = 4u;
static constexpr uint32_t DATA_SECTOR_START = 5u;  // cluster 2 → sector 5

// Returns the FAT12 value for cluster `n`.
// frame_buffer.png occupies clusters 2..2+num_png_clusters-1.
static uint16_t fat12_entry(uint32_t n, uint32_t num_png_clusters) {
  if (n == 0u) return 0xFF8u;                 // media descriptor
  if (n == 1u) return 0xFFFu;                 // volume end-of-chain
  uint32_t png_last = 1u + num_png_clusters;  // last PNG cluster
  if (n >= 2u && n <= png_last)
    return (n == png_last) ? 0xFFFu : static_cast<uint16_t>(n + 1u);
  return 0x000u;  // free
}

// Fill one FAT sector (s = 0-based index from FAT area start).
static void fill_fat_sector(uint8_t *buf, uint32_t s,
                            uint32_t num_file_clusters) {
  memset(buf, 0, DISK_SECTOR_SIZE);
  uint32_t byte_start = s * DISK_SECTOR_SIZE;
  uint32_t byte_end = byte_start + DISK_SECTOR_SIZE;
  // Each group of 3 bytes encodes two 12-bit FAT entries
  uint32_t first_group = byte_start / 3u;
  uint32_t last_group = (byte_end - 1u) / 3u;
  for (uint32_t g = first_group; g <= last_group; ++g) {
    uint16_t ea = fat12_entry(g * 2u, num_file_clusters);
    uint16_t eb = fat12_entry(g * 2u + 1u, num_file_clusters);
    uint8_t gb[3] = {
        static_cast<uint8_t>(ea & 0xFFu),
        static_cast<uint8_t>(((eb & 0x0Fu) << 4u) | ((ea >> 8u) & 0x0Fu)),
        static_cast<uint8_t>((eb >> 4u) & 0xFFu),
    };
    for (uint32_t bi = 0; bi < 3u; ++bi) {
      uint32_t fat_byte = g * 3u + bi;
      if (fat_byte >= byte_start && fat_byte < byte_end)
        buf[fat_byte - byte_start] = gb[bi];
    }
  }
}

// Checksum for 8.3 short name "FRAMEBUFPNG" = 0xCB (precomputed).
static constexpr uint8_t LFN_CHECKSUM = 0xCBu;

// Fill root directory sector with:
//   Entry 0: LFN seq=0x42 (chars 13-16 + null of "frame_buffer.png")
//   Entry 1: LFN seq=0x01 (chars 0-12 of "frame_buffer.png")
//   Entry 2: 8.3 short entry "FRAMEBUF.PNG"
static void fill_root_dir(uint8_t *buf, uint32_t file_size) {
  memset(buf, 0, DISK_SECTOR_SIZE);

  // LFN entry 2 (sequence 0x42 = last, chars 13..): 'p','n','g','\0',padding
  {
    uint8_t *e = buf;
    e[0] = 0x42u;  // last LFN entry
    // chars 13-17 (bytes 1-10): 'p','n','g','\0',0xFFFF
    const uint8_t c1[10] = {0x70, 0x00, 0x6E, 0x00, 0x67,
                            0x00, 0x00, 0x00, 0xFF, 0xFF};
    memcpy(e + 1, c1, 10);
    e[11] = 0x0Fu;
    e[12] = 0x00u;
    e[13] = LFN_CHECKSUM;
    // chars 18-23 (bytes 14-25): all 0xFFFF
    memset(e + 14, 0xFF, 12);
    e[26] = 0x00u;
    e[27] = 0x00u;
    // chars 24-25 (bytes 28-31): all 0xFFFF
    memset(e + 28, 0xFF, 4);
  }

  // LFN entry 1 (sequence 0x01, chars 0-12):
  // 'f','r','a','m','e','_','b','u','f','f','e','r','.'
  {
    uint8_t *e = buf + 32u;
    e[0] = 0x01u;
    // chars 0-4 (bytes 1-10): 'f','r','a','m','e'
    const uint8_t c1[10] = {0x66, 0x00, 0x72, 0x00, 0x61,
                            0x00, 0x6D, 0x00, 0x65, 0x00};
    memcpy(e + 1, c1, 10);
    e[11] = 0x0Fu;
    e[12] = 0x00u;
    e[13] = LFN_CHECKSUM;
    // chars 5-10 (bytes 14-25): '_','b','u','f','f','e'
    const uint8_t c2[12] = {0x5F, 0x00, 0x62, 0x00, 0x75, 0x00,
                            0x66, 0x00, 0x66, 0x00, 0x65, 0x00};
    memcpy(e + 14, c2, 12);
    e[26] = 0x00u;
    e[27] = 0x00u;
    // chars 11-12 (bytes 28-31): 'r','.'
    const uint8_t c3[4] = {0x72, 0x00, 0x2E, 0x00};
    memcpy(e + 28, c3, 4);
  }

  // 8.3 directory entry
  {
    uint8_t *e = buf + 64u;
    // Name: "FRAMEBUF" (8 bytes)
    const uint8_t name83[11] = {'F', 'R', 'A', 'M', 'E', 'B',
                                'U', 'F', 'P', 'N', 'G'};
    memcpy(e, name83, 11);
    e[11] = 0x20u;  // archive attribute
    e[26] = 0x02u;  // first cluster low = 2
    e[27] = 0x00u;
    // File size (4 bytes LE)
    e[28] = static_cast<uint8_t>(file_size & 0xFFu);
    e[29] = static_cast<uint8_t>((file_size >> 8u) & 0xFFu);
    e[30] = static_cast<uint8_t>((file_size >> 16u) & 0xFFu);
    e[31] = static_cast<uint8_t>((file_size >> 24u) & 0xFFu);
  }
}

// Fill boot sector (BPB for FAT12).
static void fill_boot_sector(uint8_t *buf, uint32_t volume_serial) {
  memset(buf, 0, DISK_SECTOR_SIZE);
  // Jump + NOP
  buf[0] = 0xEBu;
  buf[1] = 0x58u;
  buf[2] = 0x90u;
  // OEM name
  memcpy(buf + 3, "MSDOS5.0", 8);
  // BPB
  buf[11] = static_cast<uint8_t>(DISK_SECTOR_SIZE & 0xFFu);  // bytes/sector lo
  buf[12] = static_cast<uint8_t>(DISK_SECTOR_SIZE >> 8u);    // bytes/sector hi
  buf[13] = 1u;                                              // sectors/cluster
  buf[14] = 1u;   // reserved sectors lo
  buf[15] = 0u;   // reserved sectors hi
  buf[16] = 1u;   // number of FATs
  buf[17] = 16u;  // root entry count lo
  buf[18] = 0u;   // root entry count hi
  buf[19] =
      static_cast<uint8_t>(DISK_SECTOR_COUNT & 0xFFu);  // total sectors16 lo
  buf[20] =
      static_cast<uint8_t>(DISK_SECTOR_COUNT >> 8u);  // total sectors16 hi
  buf[21] = 0xF8u;                                    // media type
  buf[22] = static_cast<uint8_t>(FAT_SECTOR_COUNT & 0xFFu);  // FAT size lo
  buf[23] = static_cast<uint8_t>(FAT_SECTOR_COUNT >> 8u);    // FAT size hi
  // Sectors/track, heads, hidden sectors: left as 0
  // Extended BPB
  buf[36] = 0x80u;  // drive number
  buf[38] = 0x29u;  // extended boot signature
  buf[39] = static_cast<uint8_t>(volume_serial & 0xFFu);
  buf[40] = static_cast<uint8_t>((volume_serial >> 8u) & 0xFFu);
  buf[41] = static_cast<uint8_t>((volume_serial >> 16u) & 0xFFu);
  buf[42] = static_cast<uint8_t>((volume_serial >> 24u) & 0xFFu);
  memcpy(buf + 43, "LCDTAP     ", 11);
  memcpy(buf + 54, "FAT12   ", 8);
  buf[510] = 0x55u;
  buf[511] = 0xAAu;
}

// Generate the 512-byte sector for `lba` into `buf`.
// Boot/FAT/root sectors use pre-computed gFileSizeUsb (no framebuf needed).
// Data sectors trigger a lazy snapshot on first access so that
// processInputBuf() has had time to fill the framebuffer while the OS scanned
// the metadata sectors.
static void generate_sector(uint32_t lba, uint8_t *buf) {
  memset(buf, 0, DISK_SECTOR_SIZE);
  if (lba == 0u) {
    // The host re-reads the boot sector on each drive scan (e.g. when the user
    // opens the file explorer). Reset the snapshot flag so the next file copy
    // gets a fresh framebuffer capture.
    gSnapReady = false;
    if (gVolumeSerialUpdateReq) {
      gVolumeSerialUpdateReq = false;
      // Change the volume serial on each boot-sector read to discourage
      // host-side cache reuse of file contents.
      gVolumeSerialUsb += 1u;
    }
    fill_boot_sector(buf, gVolumeSerialUsb);
  } else if (lba >= FAT_SECTOR_START &&
             lba < FAT_SECTOR_START + FAT_SECTOR_COUNT) {
    uint32_t num_clusters =
        (gFileSizeUsb + DISK_SECTOR_SIZE - 1u) / DISK_SECTOR_SIZE;
    fill_fat_sector(buf, lba - FAT_SECTOR_START, num_clusters);
  } else if (lba == ROOT_DIR_SECTOR) {
    fill_root_dir(buf, gFileSizeUsb);
  } else if (lba >= DATA_SECTOR_START) {
    gVolumeSerialUpdateReq = true;
    if (!gSnapReady) {
      png_snapshot_init(&gSnap, gInstUsb);
      gSnapReady = true;
    }
    uint32_t byte_offset = (lba - DATA_SECTOR_START) * DISK_SECTOR_SIZE;
    for (uint32_t i = 0u; i < DISK_SECTOR_SIZE; ++i) {
      uint32_t file_off = byte_offset + i;
      buf[i] =
          (file_off < gSnap.file_size) ? png_byte_at(&gSnap, file_off) : 0u;
    }
  }
}

// =============================================================================
// USB descriptors
// =============================================================================

static constexpr uint8_t EPNUM_MSC_OUT = 0x01u;
static constexpr uint8_t EPNUM_MSC_IN = 0x81u;

enum { ITF_NUM_MSC = 0, ITF_NUM_TOTAL };

static tusb_desc_device_t const desc_device = {
    .bLength = sizeof(tusb_desc_device_t),
    .bDescriptorType = TUSB_DESC_DEVICE,
    .bcdUSB = 0x0200,
    .bDeviceClass = 0x00,
    .bDeviceSubClass = 0x00,
    .bDeviceProtocol = 0x00,
    .bMaxPacketSize0 = 64,
    .idVendor = 0x2E8Au,
    .idProduct = 0xAAAAu,
    .bcdDevice = 0x0100,
    .iManufacturer = 0x01,
    .iProduct = 0x02,
    .iSerialNumber = 0x03,
    .bNumConfigurations = 0x01,
};

#define CONFIG_TOTAL_LEN (TUD_CONFIG_DESC_LEN + TUD_MSC_DESC_LEN)

static uint8_t const desc_configuration[] = {
    TUD_CONFIG_DESCRIPTOR(1, ITF_NUM_TOTAL, 0, CONFIG_TOTAL_LEN, 0x00, 100),
    TUD_MSC_DESCRIPTOR(ITF_NUM_MSC, 0, EPNUM_MSC_OUT, EPNUM_MSC_IN, 64),
};

enum {
  STRID_LANGID = 0,
  STRID_MANUFACTURER,
  STRID_PRODUCT,
  STRID_SERIAL,
};

uint8_t const *tud_descriptor_device_cb(void) {
  return reinterpret_cast<uint8_t const *>(&desc_device);
}

uint8_t const *tud_descriptor_configuration_cb(uint8_t /*index*/) {
  return desc_configuration;
}

uint16_t const *tud_descriptor_string_cb(uint8_t index, uint16_t /*langid*/) {
  static uint16_t desc_str[32];
  uint8_t count;

  if (index == STRID_LANGID) {
    desc_str[1] = 0x0409u;
    count = 1;
  } else if (index == STRID_SERIAL) {
    pico_unique_board_id_t uid;
    pico_get_unique_board_id(&uid);
    count = 0;
    for (int i = 0; i < 8 && count < 16; ++i) {
      uint8_t b = uid.id[i];
      desc_str[1 + count++] = "0123456789ABCDEF"[b >> 4u];
      desc_str[1 + count++] = "0123456789ABCDEF"[b & 0x0Fu];
    }
  } else {
    static const char *const kStrings[] = {
        nullptr,
        "LcdTap",
        "Frame Buffer",
    };
    if (index >= sizeof(kStrings) / sizeof(kStrings[0]) || !kStrings[index])
      return nullptr;
    const char *str = kStrings[index];
    count = 0;
    while (str[count] && count < 31u) {
      desc_str[1 + count] = static_cast<uint8_t>(str[count]);
      ++count;
    }
  }

  desc_str[0] =
      static_cast<uint16_t>((TUSB_DESC_STRING << 8u) | (2u * count + 2u));
  return desc_str;
}

// =============================================================================
// TinyUSB MSC callbacks
// =============================================================================

bool tud_msc_test_unit_ready_cb(uint8_t /*lun*/) { return true; }

void tud_msc_inquiry_cb(uint8_t /*lun*/, uint8_t vendor_id[8],
                        uint8_t product_id[16], uint8_t product_rev[4]) {
  memcpy(vendor_id, "LcdTap  ", 8);
  memcpy(product_id, "Frame Buffer    ", 16);
  memcpy(product_rev, "1.0 ", 4);
}

void tud_msc_capacity_cb(uint8_t /*lun*/, uint32_t *block_count,
                         uint16_t *block_size) {
  *block_count = DISK_SECTOR_COUNT;
  *block_size = static_cast<uint16_t>(DISK_SECTOR_SIZE);
}

bool tud_msc_start_stop_cb(uint8_t /*lun*/, uint8_t /*power_condition*/,
                           bool /*start*/, bool /*load_eject*/) {
  return true;
}

bool tud_msc_is_writable_cb(uint8_t /*lun*/) { return false; }

int32_t tud_msc_read10_cb(uint8_t /*lun*/, uint32_t lba, uint32_t offset,
                          void *buffer, uint32_t bufsize) {
  if (lba >= DISK_SECTOR_COUNT) return -1;
  uint8_t sector[DISK_SECTOR_SIZE];
  generate_sector(lba, sector);
  uint32_t avail = DISK_SECTOR_SIZE - offset;
  uint32_t n = bufsize < avail ? bufsize : avail;
  memcpy(buffer, sector + offset, n);
  return static_cast<int32_t>(n);
}

int32_t tud_msc_write10_cb(uint8_t /*lun*/, uint32_t /*lba*/,
                           uint32_t /*offset*/, uint8_t * /*buffer*/,
                           uint32_t /*bufsize*/) {
  return -1;  // read-only
}

int32_t tud_msc_scsi_cb(uint8_t /*lun*/, uint8_t const /*scsi_cmd*/[16],
                        void * /*buffer*/, uint16_t /*bufsize*/) {
  return -1;
}

// =============================================================================
// Entry point
// =============================================================================

[[noreturn]] void runUsbMassStorage(lcdtap::LcdTap *inst,
                                    void (*process_input_cb)()) {
  gInstUsb = inst;
  gSnapReady = false;

  // Pre-compute file size from dimensions only (no pixel data needed yet).
  {
    const lcdtap::LcdTapConfig cfg = inst->getConfig();
    const uint32_t W = cfg.lcdWidth;
    const uint32_t H = cfg.lcdHeight;
    const uint32_t ROW_STRIDE = 5u + 1u + W * 3u;
    const uint32_t IDAT_PAYLOAD_SIZE = 2u + H * ROW_STRIDE + 4u;
    gFileSizeUsb = 8u + 25u + (4u + 4u + IDAT_PAYLOAD_SIZE + 4u) + 12u;
  }

  tusb_init();

  while (true) {
    tud_task();

    // Keep draining LCD input into the framebuffer continuously.
    // The snapshot (in generate_sector) captures Adler-32/CRC32 once per copy;
    // if the framebuffer changes afterwards the checksums may drift, but PNG
    // decoders tolerate this and the pixel content will be current.
    if (process_input_cb) {
      process_input_cb();
    }

    // Enter key (active-low) → watchdog reset back to DVI mode.
    // bootMode was already written as DVI_OUTPUT before this function ran.
    if (!gpio_get(PIN_KEY_ENTER)) {
      sleep_ms(50);
      if (!gpio_get(PIN_KEY_ENTER)) {
        watchdog_reboot(0, 0, 0);
        watchdog_enable(1, false);
        for (;;) tight_loop_contents();
      }
    }
  }
}
