#!/usr/bin/env python3
"""Embed web assets into the firmware as gzip-compressed C arrays.

Usage:
  embed_assets.py --out web_assets.cpp SRC;URL;MIME [SRC;URL;MIME ...]

Each asset is gzip-compressed (the server replies with
Content-Encoding: gzip) and emitted into one table matching the WebAsset
struct in include/web_assets.hpp.
"""

import argparse
import gzip
import pathlib


def emit_bytes(data):
    lines = []
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("assets", nargs="+", help="SRC;URL;MIME per asset")
    args = ap.parse_args()

    entries = []
    body = []
    total_raw = 0
    total_gz = 0
    for idx, spec in enumerate(args.assets):
        src, url, mime = spec.split(";")
        raw = pathlib.Path(src).read_bytes()
        # mtime=0 keeps the output deterministic across builds.
        gz = gzip.compress(raw, 9, mtime=0)
        total_raw += len(raw)
        total_gz += len(gz)
        body.append(f"// {url} <- {pathlib.Path(src).name} "
                    f"({len(raw)} -> {len(gz)} bytes)")
        body.append(f"static const uint8_t ASSET_{idx}[] = {{")
        body.append(emit_bytes(gz))
        body.append("};\n")
        entries.append(
            f'    {{"{url}", "{mime}", ASSET_{idx}, sizeof(ASSET_{idx}), 1}},'
        )

    out = [
        "// Generated by tools/embed_assets.py — do not edit.",
        f"// {len(entries)} assets, {total_raw} bytes raw, "
        f"{total_gz} bytes gzipped.",
        "",
        '#include "web_assets.hpp"',
        "",
        *body,
        "const WebAsset WEB_ASSETS[] = {",
        *entries,
        "};",
        "",
        f"const int WEB_ASSET_COUNT = {len(entries)};",
        "",
    ]
    pathlib.Path(args.out).write_text("\n".join(out))
    print(f"embed_assets: {len(entries)} assets, "
          f"{total_raw} -> {total_gz} bytes")


if __name__ == "__main__":
    main()
